// This is a comment 
let x @ Int = 5

type Fruit 
    .name    @ String
    .age     @ Int
    .sibling @ Fruit?

let myFruit @ Fruit = #
    .name <- `Pineapple`
    .age  = 123.456e-10
    .sibling = nil
    
if score is > 70 and is <= 80
    print: `Good job!`

if myFruit or hisFruit isnt :sweet
    print: `Someone's fruit is not sweet`

if john is :nice and mary is :sweet
    print: `Wow`

let numbers = split: `3,4,5,6` :by: `,`

function 
split: target@String :by: separator@String >> String[]
    throw `Not implemented yet`


        
